import 'dart:io';

import 'package:dopamine_drop/version.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  group('version', () {
    // lib/version.dart is generated by tool/make_version.py. If someone bumps
    // pubspec and forgets to re-run it, the home screen and the Play listing
    // disagree — and the number in a bug report points at the wrong build.
    test('matches pubspec.yaml', () {
      final pubspec = File('pubspec.yaml').readAsStringSync();
      final match = RegExp(r'^version:\s*([0-9][^\s+]*)\+([0-9]+)\s*$',
              multiLine: true)
          .firstMatch(pubspec);

      expect(match, isNotNull, reason: 'pubspec needs `version: x.y.z+build`');
      expect(kAppVersion, match!.group(1),
          reason: 'stale lib/version.dart — run: python3 tool/make_version.py');
      expect(kBuildNumber, int.parse(match.group(2)!),
          reason: 'stale lib/version.dart — run: python3 tool/make_version.py');
    });

    test('the label carries both numbers', () {
      // The marketing version is what a player quotes; the build number is what
      // actually identifies the artefact on Play.
      expect(kVersionLabel, 'v$kAppVersion ($kBuildNumber)');
    });

    test('the build number is a positive integer, as Play requires', () {
      expect(kBuildNumber, greaterThan(0));
    });
  });
}
