import 'dart:async';

import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

/// Tap-level feedback: sound and haptics.
///
/// Called on far more events than a typical app would be, on purpose. The
/// feedback loop is the product — a solve that lands silently is most of the
/// reward gone.
///
/// Sounds are generated by `tool/make_sfx.py` rather than sourced, so the
/// waveforms stay editable in the repo. See that file to retune them.
class GameFeedback {
  GameFeedback({this.sound = true, this.haptics = true});

  bool sound;
  bool haptics;

  /// A small pool, because a fast player retriggers a sound before the previous
  /// one has finished and a single player would cut itself off mid-note.
  static const _voices = 4;
  /// Audio init has to be bounded. A missing or wedged platform implementation
  /// leaves the plugin's own futures pending forever, and an unbounded await
  /// here would keep a warm-up alive for the life of the process.
  static const _initTimeout = Duration(seconds: 3);

  final List<AudioPlayer> _pool = [];
  int _next = 0;
  bool _ready = false;

  /// Whether sound will actually come out. False is a normal state, not an
  /// error: the game is fully playable in silence.
  bool get ready => _ready;

  /// Safe to call more than once; safe to skip entirely (every play is a no-op
  /// until it completes). Never awaited on the UI path.
  ///
  /// Runs inside a guarded zone because the plugin starts initialising from the
  /// AudioPlayer constructor and reports failure on a future the caller never
  /// gets a handle on — a plain try/catch around this loop catches the
  /// synchronous half only, and the rest surfaces as an unhandled error on any
  /// device where audio init fails.
  Future<void> warmUp() {
    if (_ready || _pool.isNotEmpty) return Future.value();
    final done = Completer<void>();

    void giveUp(Object error) {
      // No audio device, a locked-down emulator, a platform without the plugin:
      // the game is fully playable in silence, so this is never fatal.
      _ready = false;
      _pool.clear();
      debugPrint('Dopamine Drop: audio unavailable ($error)');
      if (!done.isCompleted) done.complete();
    }

    runZonedGuarded(() async {
      try {
        await Future(() async {
          for (var i = 0; i < _voices; i++) {
            final player = AudioPlayer(playerId: 'dd_$i')
              ..setReleaseMode(ReleaseMode.stop);
            await player.setPlayerMode(PlayerMode.lowLatency);
            _pool.add(player);
          }
        }).timeout(_initTimeout);
        _ready = true;
        if (!done.isCompleted) done.complete();
      } catch (e) {
        giveUp(e);
      }
    }, (error, _) => giveUp(error));

    return done.future;
  }

  void _buzz(void Function() pattern) {
    if (haptics) pattern();
  }

  void _play(String name, {double volume = 1.0}) {
    if (!sound || !_ready || _pool.isEmpty) return;
    final player = _pool[_next];
    _next = (_next + 1) % _pool.length;
    unawaited(() async {
      try {
        await player.stop();
        await player.setVolume(volume);
        await player.play(AssetSource('sfx/$name.wav'));
      } catch (_) {
        // A dropped effect is not worth interrupting a run over.
      }
    }());
  }

  void tap() {
    _buzz(HapticFeedback.selectionClick);
    _play('tap', volume: 0.55);
  }

  void solved(int streak) {
    // Both channels climb with the streak: the note steps up a scale and the
    // haptic gets heavier, so a run building is something you hear and feel.
    _buzz(streak >= 8
        ? HapticFeedback.heavyImpact
        : streak >= 4
            ? HapticFeedback.mediumImpact
            : HapticFeedback.lightImpact);
    final step = (streak.clamp(1, 20) - 1) ~/ 4 + 1;
    _play('good${step.clamp(1, 5)}');
  }

  void missed() {
    _buzz(HapticFeedback.vibrate);
    _play('bad', volume: 0.8);
  }

  void runOver() {
    _buzz(HapticFeedback.heavyImpact);
    _play('over');
  }

  void levelUp() {
    _buzz(HapticFeedback.heavyImpact);
    _play('levelup');
  }

  void tick() => _play('tick', volume: 0.5);

  void go() {
    _buzz(HapticFeedback.mediumImpact);
    _play('go');
  }

  Future<void> dispose() async {
    for (final player in _pool) {
      await player.dispose();
    }
    _pool.clear();
    _ready = false;
  }
}
