// GENERATED BY tool/make_version.py — DO NOT EDIT.
// Bump `version:` in pubspec.yaml and re-run the script.

/// Marketing version, e.g. "1.2.0". Matches `version:` in pubspec.yaml.
const String kAppVersion = '0.3.0';

/// Android versionCode / iOS build number — the integer after the `+`.
///
/// This is the number Play shows and the one a support request needs, so it is
/// displayed alongside the marketing version rather than hidden.
const int kBuildNumber = 3;

/// What the home screen shows: "v0.1.0 (1)".
const String kVersionLabel = 'v0.3.0 (3)';
