#!/usr/bin/env python3
"""Generate lib/version.dart from pubspec.yaml.

A compile-time constant rather than package_info_plus: the version label is one
line of chrome on the home screen, and a platform-channel plugin for it would
mean an async read, a failure path, and a mock in every widget test.

    python3 tool/make_version.py

`test/version_test.dart` fails if the generated file drifts from pubspec, so a
forgotten regeneration after a version bump cannot ship.
"""
import re
import sys
from pathlib import Path

root = Path(__file__).resolve().parent.parent
pubspec = (root / "pubspec.yaml").read_text(encoding="utf-8")

match = re.search(r"^version:\s*([0-9][^\s+]*)\+([0-9]+)\s*$", pubspec, re.M)
if not match:
    sys.exit("pubspec.yaml needs a `version: x.y.z+build` line")

name, build = match.group(1), match.group(2)

(root / "lib" / "version.dart").write_text(
    f'''// GENERATED BY tool/make_version.py — DO NOT EDIT.
// Bump `version:` in pubspec.yaml and re-run the script.

/// Marketing version, e.g. "1.2.0". Matches `version:` in pubspec.yaml.
const String kAppVersion = '{name}';

/// Android versionCode / iOS build number — the integer after the `+`.
///
/// This is the number Play shows and the one a support request needs, so it is
/// displayed alongside the marketing version rather than hidden.
const int kBuildNumber = {build};

/// What the home screen shows: "v0.1.0 (1)".
const String kVersionLabel = 'v{name} ({build})';
''',
    encoding="utf-8",
)
print(f"lib/version.dart -> v{name} ({build})")
